import { motion } from 'framer-motion';
import { useInView } from '../hooks/useHooks';
import { HiSparkles } from 'react-icons/hi';

const SummaryCard = ({ aiSummary }) => {
  const { ref, inView } = useInView(0.2);

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 20 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.5 }}
      className="relative overflow-hidden rounded-3xl p-[1px] mb-8"
      style={{
        background: 'linear-gradient(135deg, rgba(99,102,241,0.5), rgba(139,92,246,0.2), rgba(0,212,255,0.1))',
      }}
    >
      <div className="relative glass-card p-6 md:p-8 rounded-[23px] overflow-hidden">
        {/* Animated gradient background */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-gradient-to-br from-indigo-500/10 via-purple-500/10 to-transparent rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 animate-pulse-slow pointer-events-none" />
        
        <div className="relative z-10 flex flex-col md:flex-row gap-6 items-start">
          <div className="shrink-0 w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
            <HiSparkles className="text-white text-2xl" />
          </div>
          
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-2">
              <h3 className="text-white font-semibold text-lg">AI Executive Summary</h3>
              <span className="tag-pill bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 text-xs">
                Generated by SpendWise AI Engine
              </span>
            </div>
            
            <div className="space-y-4">
              <p className="text-slate-300 leading-relaxed text-sm whitespace-pre-line">
                {aiSummary || "..."}
              </p>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default SummaryCard;
